### PR TITLE
upgrade druid version

### PR DESCRIPTION
**Pull request by Smartappli**

### CODE REVIEW

**Comment by jihoonson** [comment]
@Smartappli thanks for the contribution! The latest Druid version is 0.12.1, and we might release 0.12.2 in a few weeks. Would you change the Druid version to 0.12.1?

**Comment by jihoonson** [comment]
@Smartappli sorry I forgot to ask before merging. Would you fill out our CLA here (http://druid.io/community/cla.html)?

**Comment by Smartappli** [comment]
@jihoonson done ;)

**Comment by jihoonson** [comment]
@Smartappli thanks!

**Pull request merged**
